### ISSUE TITLE
Create Number of Words per Document Histogram for Full Disclosure Mailing List

### ISSUE THREAD

**Issue by kavashashank** [sailuh/perceive#52]
I will start with creating a single histogram of a number of words per document (email reply) in 2012, and then modify the code for the other years.

A second step will be to create one histogram per month instead of per year, for a total of 12 histograms per year.

**Comment by carlosparadis** [comment]
Thanks for the PR. I made a few request for changes.

**Comment by carlosparadis** [comment]
@kavashashank Thanks for the time today so we could cover all the pending parts. We covered a lot of ground and reviews on all these PRs! I am taking the ball on this Notebook since I still want to make a few minor changes. As such, this issue will remain open, but note the assignee is now changed to me rather than you, so there is no further action on your part on this issue :-) 

I gave you some guidelines on the next part, so feel free to get started. I will create an issue with some more details on it later on.

Thanks!

**Comment by carlosparadis** [comment]
See #71
