### ISSUE TITLE
Run ontology visualization code on existing versions and move on to CAPEC 2.11

### ISSUE THREAD

**Issue by vaishvel** [sailuh/perceive#55]
I am familiarizing myself with Vignesh's code on versions prior to 2.10 and after successfully running them I plan to generate the visualization for CAPEC 2.11 .

**Comment by carlosparadis** [comment]
Sounds good, don't forget to check [FoamTree](http://get.carrotsearch.com/foamtree/demo/). The general idea of the code was basically the following:

- Data on CAPEC is exposed as **XML** in **4 trees**. 
- FoamTree is a Javascript block of code that wants to see a single Tree in **JSON**. 

As such Vignesh code needs to do 2 big steps:

- Convert 4 trees into 1 tree.
- Transforms XML into JSON format.

Keep this in mind as you navigate through it!

**Comment by vaishvel** [comment]
Thanks Carlos. 
 I'll work on that this week and reach out in case any clarifications are required.

**Comment by vaishvel** [comment]
I ran the code and generated visualizations for CAPEC v2.10 and CAPEC v2.11 .  I'm also continuing to explore FoamTree.  I currently have a holistic understanding of Vigneshs code and am studying it in detail.
If required, I could work on the Notebook to expand on the initial process required  to generate the visualization output for CAPEC.

**Comment by carlosparadis** [comment]
Hmm.. were you able to obtain as output also the following files when providing capec_v2.11.xml as input?

 - capec_v2.11 [Edges].csv
 - capec_v2.11 [Nodes].csv
 - capec_v2.11.html
 - capec_v2.11.json

Could you pass them on Slack too? Was there anything you had difficulties with when running or took more steps than you considered needed? 

And could you describe overall what steps you needed to go through in order to get it to work? 

What would you recommend / how extend from what you saw on FoamTree visualization in other websites?

**Comment by carlosparadis** [comment]
I spent some time doing the exercise myself. 

See #61 and the associated new [README.md file that has been added](https://github.com/sailuh/perceive/tree/master/Notebooks/CAPEC). 

This wraps-up this issue, which was to guarantee the existing pipeline works and is easy-to-use. Now that you are familiar with foamtree and with what we have, we move on to the actual work :-) I will close this issue and open a new one.
