### ISSUE TITLE
Reviewing existing schema on model.mwb

### ISSUE THREAD

**Issue by st252099074** [sailuh/perceive#57]
Hi Carlos,
    One of my take aways from the meeting last Saturday was looking for potential modifications for the existing database schema. The desired database should be able to dissect the raw data (Email threads from Full Discourse and Bugtraq, correct me if I am wrong) and store them into respective tables (presumably a table for the bodies, a table for the titles, etc.). Here is I am thinking...
   1. The database schema for the Email list should be able to distinguish the Emails from Full Discourse and Bugtraq, but still, maintain a degree of connections (e.g. a common author).

  2. You mentioned that you would like to see RAW data turns into Documentation in the database schema.
How do you think to achieve the task by creating a few VIEWs in the database schema? 

  3.  I have cloned the PERCEIVE folder from the Github. But the "model.mwb" in Database folder won't be opened properly in MySQL Workbench. After opening the model in MySQL Workbench, I only received a blank diagram..Although the existing screen shot displays the tables and their relationships, it doesn't show all the columns in every table. It would be helpful if there is a way to get the model.mwb working so I may optimize the database based on the information in Corpus.

 4. Could you explain a little bit about the purpose of using Hadoop in this project? I know Hadoop distributes the information to different servers to optimize the speed of retrieving data and the capacity of storing large file. Are we using Hadoop to host our database once it is designed completely? Maybe I have answered my own question, but still, want to double check.

**Comment by carlosparadis** [comment]
> The database schema for the Email list should be able to distinguish the Emails from Full Discourse and Bugtraq, but still, maintain a degree of connections (e.g. a common author).

> You mentioned that you would like to see RAW data turns into Documentation in the database schema.

Raw data turn into `Documents` is a conceptual expression, what this really translates to in practice is that some tables should hold the raw data as is, and other should contain only the relevant portion of the data that will be used further in the pipeline. One way can be the body, other way can be body+title, etc. What matters is that in just looking at the tables and their FKs we can have an idea of how the transformations were performed. 

> How do you think to achieve the task by creating a few VIEWs in the database schema?

It is not a bad idea, but since we will be doing a lot of read operations on the later tables, a VIEW would slow down the pipeline. It is best to have the data persist in the database due to that. 

> I have cloned the PERCEIVE folder from the Github. But the "model.mwb" in Database folder won't be opened properly in MySQL Workbench. After opening the model in MySQL Workbench, I only received a blank diagram..Although the existing screen shot displays the tables and their relationships, it doesn't show all the columns in every table. It would be helpful if there is a way to get the model.mwb working so I may optimize the database based on the information in Corpus.

Could you have your roomate try to do the same and let me know if also doesn't work for him? Last I checked this was working! 

> Could you explain a little bit about the purpose of using Hadoop in this project? I know Hadoop distributes the information to different servers to optimize the speed of retrieving data and the capacity of storing large file. Are we using Hadoop to host our database once it is designed completely? Maybe I have answered my own question, but still, want to double check.

I will explain more for the sake of clarity since Yue is the one handling this portion. For now, we are interested in seeing how this scale up when compared to Postgres and how much effort it is to maintain. Postgres will not be deployed inside hadoop, but we can deploy other databases that benefit from HDFS later down the road.

Let me know if you need further clarifications :)

**Comment by st252099074** [comment]
Quick update. The "Model" file is working. Digging into the structure over the course of this weekend.

**Comment by st252099074** [comment]
For the threads with replies in Full Disclosure which of the following is desired:

1) Depicting parent-child relationships as the structure "model" does. We will be able to tell the starters and their following replies within the common topics.

2) We only want to group the Emails in respect of their topics regardless which Emails started the conversation and which Emails are the replies.

**Comment by carlosparadis** [comment]
We should plan for 1. as 2. can be described in 1 by just having the ancestor pointing to the same id.

**Comment by carlosparadis** [comment]
This task will be deferred until a later date.
