### ISSUE TITLE
Create foamtree for CWE research concept view. 

### ISSUE THREAD

**Issue by carlosparadis** [sailuh/perceive#64]
The idea is similar to #55, and CWE has a very similar format to the data as CAPEC. Ideally, downloading the .xml file and running would suffice, but there was a problem when Vignesh attempted to do this: 

In the XML file, one of the 4 tables contained no further reference to the remaining ones in the same way the ones in CAPEC did. 

We need to find a way to circumvent the issue and recreate the visualizations, as well as pinpoint the exact details on why one table does not refer another.

**Comment by carlosparadis** [comment]
Hi @vaishvel, were you able to move forward in this front?

**Comment by vaishvel** [comment]
Hi @carlosviansi , I'm working on the script and hope to have a clear approach to close this gap in a couple of days. I'm also working on the Notebook that represents the current work with the overall goals of Perceive.

**Comment by carlosparadis** [comment]
@vaishvel thanks for the update Vaish :-) Feel free to share intermediate one work if you would like to confirm anything or have any questions!

**Comment by vaishvel** [comment]
Hi @carlosviansi , during my analysis of the cwec_v2.11.xml code (focusing on the inter-table relationships under the View IDs 1000 and 699), the irregularities I found exist in View 699.

In the inter-table relationships shown in cwe, I found the below Compound Elements to relate to their respective Weakness tables under primary ID 1000 instead of primary ID 699 in the xml code:
Category 417 -- Compound Element 426 -- Weaknesses -- 216, 471, 275
Category 361 -- Compound Element 384 -- Weaknesses -- 472, 346, 441
Category 442 -- Compound Element 352 -- Weaknesses -- 642, 613, 346, 441
 

![a](https://user-images.githubusercontent.com/31453457/31060854-68e7537a-a6e8-11e7-95f1-de9ddb000ada.PNG)
![b](https://user-images.githubusercontent.com/31453457/31060855-6d08f378-a6e8-11e7-96bc-eac7d81ada02.PNG)
![c](https://user-images.githubusercontent.com/31453457/31060856-709c84be-a6e8-11e7-8568-e13ee03db526.PNG)


I will continue to analyse the deeper trees to find similar gaps.

**Comment by vaishvel** [comment]
Hi @carlosviansi , after extensive analysis of the CWE research concepts and development concepts,
I found the below irregularities:
1)	The below Weakness element is under primary ID 1000 instead of primary ID 699 in the xml code:
![d](https://user-images.githubusercontent.com/31453457/31857521-b03e0d4c-b6ae-11e7-98ff-60eb17e90f50.png)
 
2)	The following weaknesses don’t specify View ID 699 as the primary id, in some cases labeling View ID 1000 as the primary id:
	Weakness 126: 
 ![weakness 126 - no primary id](https://user-images.githubusercontent.com/31453457/31857492-3bdadbb0-b6ae-11e7-9c73-ae0fc76e9d09.PNG)

	Weakness 138:
![weakness 138 - no primary id](https://user-images.githubusercontent.com/31453457/31857493-3be7db44-b6ae-11e7-8506-92fe62512d02.PNG)

	Weakness 248:
![weakness 248 - no primary id](https://user-images.githubusercontent.com/31453457/31857494-3bf2e016-b6ae-11e7-9c8c-1a7383f66d84.PNG)

	Weakness 382:
![weakness 382 - no primary id](https://user-images.githubusercontent.com/31453457/31857495-3bfc8486-b6ae-11e7-8b8d-e8a0cccbf214.PNG)

	Weakness385: 
![weakness 385 - no primary id](https://user-images.githubusercontent.com/31453457/31857496-3c076ae0-b6ae-11e7-9f76-67eb24c31c1e.PNG)

	Weakness 574: 
![weakness 574 - no primary id](https://user-images.githubusercontent.com/31453457/31857497-3c291bae-b6ae-11e7-9891-281fb5200c53.PNG)

	Weakness 652: 
![weakness 652 - no primary id](https://user-images.githubusercontent.com/31453457/31857498-3c376c54-b6ae-11e7-9242-6cfb086e74a1.PNG)

	Weakness 681: 
![weakness 681 - no primary id](https://user-images.githubusercontent.com/31453457/31857499-3c44554a-b6ae-11e7-816b-50be73733b37.PNG)

	Weakness 779: 
![weakness 779 - no primary id](https://user-images.githubusercontent.com/31453457/31857500-3c508c48-b6ae-11e7-9889-5f34337d7450.PNG)

	Weakness 914:
![weakness 914- primary1000](https://user-images.githubusercontent.com/31453457/31857501-3c5e602a-b6ae-11e7-8582-abd2663bbeee.PNG)

**Comment by carlosparadis** [comment]
Foamtree was completed, I will update the notebooks with images eventually.
